export const data = {
    personajes : {
        mugiwaras: [
            {
                imagen: "./assets/personajes/luffy.webp",
                nombre: 'Monkey D. Luffy',
                fruta: 'Gomu-Gomu no mi',
                rol: 'Capitan',
                edad: 19,
                recompensa: '$3,000,000,000',
                estado: 'Vivo',
                altura: "172cm",
                epiteto: "Sombrero de paja Luffy",
                nacimiento: "5 de mayo",
                origen: "East Blue",
                aparicion: "Capitulo 1; Episodio 1",
                tipoFruta: "Zoan Mitica",
                descripcion: 'Monkey D. Luffy (モンキー・Ｄ・ルフィ Monkī Dī Rufi?), más conocido como Luffy «Sombrero de Paja» (麦わらのルフィ Mugiwara no Rufi), es el protagonista principal de la serie de manga y anime One Piece. Es el capitán y fundador de los Piratas de Sombrero de Paja así como un de los Cuatro Emperadores que gobiernan los mares del Nuevo Mundo. Comió una fruta del diablo llamada fruta Gomu Gomu, que le convirtió en un hombre de goma. Además de esto, posee varias habilidades que le hacen ser un pirata más que especial; un gran ejemplo de ello es la capacidad de usar el haoshoku haki ―que sólo lo posee una persona dentro de un millón― y poseer también los otros dos tipos de haki.',
                descripcion2: 'Luffy pertenece a una familia plagada de personajes conocidos mundialmente: es hijo del líder del Ejército Revolucionario y criminal más buscado del mundo, Monkey D. Dragon; nieto del héroe de la Marina y anterior vicealmirante Monkey D. Garp, hermano adoptivo del conocido pirata Ace "Puño de Fuego" ―antiguo comandante de la segunda división de los Piratas de Barbablanca―, así como del oficial general del Ejército Revolucionario, Sabo. Su objetivo en la vida es convertirse en el próximo Rey de los Piratas, encontrar el legendario tesoro conocido como el "One Piece", que perteneció al anterior Rey de los Piratas Gol D. Roger, y conquistar el Nuevo Mundo liderando una tripulación formada por grandes piratas.'
            },
            {
                imagen: "./assets/personajes/zoro.webp",
                nombre: 'Roronoa Zoro',
                fruta: 'Sin fruta',
                rol: 'Espadachin',
                edad: 21,
                recompensa: '$1,111,000,000',
                estado: 'Vivo',
                altura: "181cm",
                epiteto: "El Cazador de Piratas",
                nacimiento: "11 de noviembre",
                origen: "East Blue",
                aparicion: "Capitulo 2; Episodio 1",
                tipoFruta: "Sin Fruta",
                descripcion: 'Roronoa Zoro (ロロノア・ ゾロ Roronoa Zoro?), conocido como El Cazador de Piratas (海賊狩り Kaizoku Gari?),[16] es el primer pirata que se unió a Monkey D. Luffy, y el principal combatiente de los Piratas de Sombrero de Paja, uno de sus dos espadachines y uno de los oficiales principales de la Gran Flota de Sombrero de Paja, así como un antiguo cazarrecompensas.',
                descripcion2: 'Nacido en el East Blue, Zoro es hijo de Tera y Roronoa Arashi, nieto de Shimotsuki Furiko y Roronoa Pinzoro, y sobrino nieto de Shimotsuki Ushimaru, lo que le convierte en descendiente matrilineal tanto de la familia Shimotsuki del País de Wano como del legendario samurái Shimotsuki Ryuma. Fue el primer miembro en unirse a la tripulación, y es considerado parte del Trío Monstruoso (怪物三人組 Kaibutsu San-ningumi) junto a Luffy y Sanji. Su sueño es convertirse en el mejor espadachín del mundo. Zoro junto a su capitán, también es considerado uno de los Once Supernovas que forman parte de «la peor generación».Obtuvo su primera recompensa de $60.000.000 tras el arco de Arabasta. Más tarde aumentó a Belly120.000.000 tras el incidente de Enies Lobby, y de nuevo a Belly320.000.000 tras el arco de Dressrosa. Tras el asalto a Onigashima, su recompensa aumentó a $1.111.000.000, siendo la segunda más alta de la tripulación solo superada por la de Luffy.'
            },
            {
                imagen: "./assets/personajes/nami.webp",
                nombre: 'Nami',
                fruta: 'Sin fruta',
                rol: 'Navegante',
                edad: 20,
                recompensa: '$366,000,000',
                estado: 'Viva',
                altura: "170cm",
                epiteto: "La Gata Ladrona",
                nacimiento: "3 de julio",
                origen: "East Blue",
                aparicion: "Capitulo 8; Episodio 1",
                tipoFruta: "Sin Fruta",
                descripcion: 'Nami (ナミ Nami), apodada Gata Ladrona (泥棒猫 Dorobō Neko), es una pirata y la navegante de los Piratas del Sombrero de Paja , así como una de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el tercer miembro de la tripulación y la segunda en unirse, haciéndolo oficialmente durante el arco de Arlong Park. Ella era anteriormente un miembro de los Piratas de Arlong e inicialmente se unió a los de Sombrero de Paja con el fin de robarles, pero se unió oficialmente tras rebelarse contra Arlong y su posterior derrota a manos de Luffy. Actualmente posee una recompensa de $366.000.000.',
                descripcion2: 'Nami es una chica joven, de tamaño normal con una constitución delgada, y que originalmente tenía el pelo corto de color naranja. En el anime ella fue el primer personaje principal en aparecer en el episodio 1 antes que Luffy (aunque en el manga apareció al principio del arco de la ciudad Orange). Muchas personas la consideran muy atractiva y hermosa, comparándola en una ocasión con una diosa. Ella tiene un tatuaje azul (negro en el manga) en su hombro izquierdo que representa una mandarina y un molinillo (un homenaje a Bell-mère y Genzo, respectivamente), en donde ella antes tenía un tatuaje que indicaba que ella era miembro de la banda de Arlong.'
            },
            {
                imagen: "./assets/personajes/usopp.webp",
                nombre: 'Usopp',
                fruta: 'Sin fruta',
                rol: 'Francotirador',
                edad: 19,
                recompensa: '$500,000,000',
                estado: 'Vivo',
                altura: "176cm",
                epiteto: "Rey de los Tiradores",
                nacimiento: "1 de abril",
                origen: "East Blue",
                aparicion: "Capitulo 23; Episodio 8",
                tipoFruta: "Sin Fruta",
                descripcion: 'Usopp (ウソップ Usoppu) es el francotirador de los Piratas de Sombrero de Paja y uno de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el cuarto miembro de la tripulación y el tercero en unirse oficialmente. A pesar de abandonar la banda en el arco de Water 7, se volvió a unir en el arco del regreso a Water 7.Es proveniente de la villa Syrup en el East Blue. Ahí ejerció como capitán de los Piratas de Usopp, pero tras los eventos del arco de Villa Syrup, se unió a los Sombrero de Paja. Su sueño es convertirse en un valiente guerrero de los mares como su padre. Su recompensa actual es de $500.000.000.',
                descripcion2: 'Durante la mayor parte de la historia, Usopp es un joven de piel blanca pero bronceada y constitución delgada, ojos grandes y redondos, labios gruesos y pelo negro muy rizado de longitud media; aunque el rasgo más llamativo de su apariencia es, sin duda, su larga nariz (que aparentemente es una alusión al personaje de Pinocho, el protagonista de un cuento del mismo nombre). Este llamativo rasgo fue aparentemente heredado de su madre, mientras que en todos los demás rasgos de su rostro es prácticamente idéntico a su padre (esto es notable incluso teniendo en cuenta que el aspecto de su padre ha sufrido muchos cambios con el paso del tiempo; sobre todo en lo referente al cabello, que pasa de ser igual de negro y rizado que el de su hijo a ser rubio y llevar rastas). En lo que se refiere a su cuerpo, Usopp es algo más alto que Luffy y su constitución es, si hacemos comparación, más semejante a la de Sanji y del capitán, que a la de Zoro o mucho menos Franky.'
            },
            {
                imagen: "./assets/personajes/sanji.webp",
                nombre: 'Vismoke Sanji',
                fruta: 'Sin fruta',
                rol: 'Cocinero',
                edad: 21,
                recompensa: '$1,032,000,000',
                estado: 'Vivo',
                altura: "180cm",
                epiteto: "Piernas Negras",
                nacimiento: "2 de marzo",
                origen: "North Blue",
                aparicion: "Capitulo 43; Episodio 20",
                tipoFruta: "Sin Fruta",
                descripcion: 'Sanji (サンジ Sanji?), conocido como Pierna Negra (黒脚 Kuro Ashi) y nacido como Vinsmoke Sanji (ヴィンスモーク・サンジ Vinsumōku Sanji), es el cocinero de los Piratas de Sombrero de Paja, así como uno de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el quinto miembro de la tripulación, y el cuarto en unirse. Él nació en el North Blue, siendo el primer tripulante en no ser originario del East Blue.',
                descripcion2: 'Nacido como el cuarto hijo de la familia Vinsmoke, y por ende como uno de los príncipes del Reino de Germa, Sanji se exilió de su país y renegó de su familia, yéndose al East Blue y pasando a trabajar como cocinero en el Baratie, hasta que decidió unirse a la banda. Es considerado parte del Trío Monstruoso (怪物三人組 Kaibutsu San-ningumi) junto a Luffy y Zoro; y, como tal, es uno de los combatientes más fuertes de la tripulación. Su sueño es encontrar el mar legendario conocido como All Blue.Actualmente posee una recompensa de $1.032.000.000 que obtuvo después de los acontecimientos del arco del País de Wano, siendo la cuarta recompensa más alta de la tripulación superada por la de Luffy, Zoro y Jinbe'

            },
            {
                imagen: "./assets/personajes/chopper.webp",
                nombre: 'Tony Tony Chopper',
                fruta: 'Hito-Hito no mi',
                rol: 'Medico',
                edad: 17,
                recompensa: '$1000',
                estado: 'Vivo',
                altura: "90cm",
                epiteto: "El Amante del Algodón de Azúcar",
                nacimiento: "24 de diciembre",
                origen: "Paradise",
                aparicion: "Capitulo 134; Episodio: 81",
                tipoFruta: "Zoan",
                descripcion: 'Tony Tony Chopper (トニートニー・チョッパー Tonī Tonī Chopā?) es el médico de los Piratas de Sombrero de Paja, así como uno de los oficiales principales de la Gran Flota de Sombrero de Paja. Es un reno que comió la fruta Hito Hito de la isla de Drum. Él es el sexto miembro de la tripulación y el quinto en unirse a ella.',
                descripcion2: 'Es un Reno de nariz azul que comió la fruta Hito Hito, adquiriendo forma e inteligencia humana. La mayor parte del tiempo, Chopper mantiene un tamaño pequeño, con forma de reno-humanoide (brain point); las habilidades de su fruta del diablo le permiten cambiar de apariencia dependiendo de la situación. El cuerno izquierdo de Chopper tiene una placa metálica alrededor porque se lo rompió en una pelea cuando era más joven, y Hiriluk se lo trató. Chopper tiene un rasgo destacable que ningún otro reno tiene: su nariz azul.Varios personajes en One Piece han pensado al principio que Chopper es un mapache (del japonés "tanuki"), debido al aspecto que tiene cuando se halla en su forma "Brain Point". En realidad se trata de un juego de palabras: el término japonés "tonakai", que significa reno, es de donde viene el "Tony" del nombre completo de Chopper. A diferencia de su "Brain Point", cuando Chopper está en su "Heavy Point", es confundido con un gorila o un yeti.'
            },
            {
                imagen: "./assets/personajes/robin.webp",
                nombre: 'Nico Robin',
                fruta: 'Hana-Hana no mi',
                rol: 'Arqueologa',
                edad: 30,
                recompensa: '$930,000,000',
                estado: 'Viva',
                altura: "188cm",
                epiteto: "La Niña Demonio",
                nacimiento: "6 de febrero",
                origen: "West Blue",
                aparicion:"Cpitulo 114; Episodio 67",
                descripcion: 'Nico Robin (ニコ・ロビン Niko Robin), también conocida por sus epítetos: Niña Demonio (悪魔の子 Akuma no Ko) y La Luz de la Revolución (革命の灯 Kakumei no Tomoshibi) es la arqueóloga de los Piratas de Sombrero de Paja, así como una de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el séptimo miembro de la tripulación y el sexto en unirse, haciéndolo al final del arco de Arabasta.',
                descripcion2: 'Es introducida como una de los antagonistas secundarios más destacados de la saga de Arabasta siendo la vicepresidenta de Baroque Works y la mano derecha de Crocodile. Sin embargo, luego de ser salvada por Monkey D. Luffy de morir a manos de Crocodile y la posterior derrota del ex Señor de la Guerra del Mar se une a la tripulación. Dejó temporalmente a la banda durante el arco de Water 7, pero se reincorporó al final del arco de Enies Lobby tras la derrota del CP9 a manos de los Piratas de Sombrero de Paja.Su sueño es conocer la verdadera historia investigando en los poneglyphs. Actualmente ofrecen una recompensa de $930.000.000 por su cabeza, siendo la quinta más alta de toda su tripulación.'
            },
            {
                imagen: "./assets/personajes/franky.webp",
                nombre: 'Franky',
                fruta: 'Sin fruta',
                rol: 'Carpintero',
                edad: 36,
                recompensa: '$394,000,000',
                estado: 'Vivo',
                altura: "240cm",
                epiteto: "El Hombre de Hierro",
                nacimiento: "9 de marzo",
                origen: "South Blue",
                aparicion: "Capitulo 329; Episodio 233",
                tipoFruta: "Sin Fruta",
                descripcion: 'Franky (フランキー Furankī), apodado el Hombre de Hierro (鉄人 tetsujin), es el carpintero naval de los Piratas de Sombrero de Paja y uno de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el octavo miembro de la tripulación y el séptimo en unirse, haciéndolo al final del arco del regreso a Water 7.',
                descripcion2: "Nacido como Cutty Flam (カティ・フラム Kati Furamu) y originario del South Blue, Franky fue un miembro de los Tom's Workers, hasta que un incidente que dañó su cuerpo le requirió convertirse en un cyborg para curarse. Posteriormente se convertiría en el líder de la familia Franky, un grupo de cazarrecompensas y desmanteladores de barcos, adoptando su nombre actual para ocultar su identida.Franky y sus seguidores eran originalmente enemigos de los Sombrero de Paja al principio del arco de Water 7, hasta que las circunstancias les obligaron a convertirse en aliados al final del mismo arco y del arco de Enies Lobby. El sueño de Franky es crear un barco y circunnavegar el mundo con él, y construyó el Thousand Sunny y se unió a los Piratas de Sombrero de Paja para cumplir su sueño."
            },
            {
                imagen: "./assets/personajes/brook.webp",
                nombre: 'Brook',
                fruta: 'Yomi-Yomi no mi',
                rol: 'Musico',
                edad: 90,
                recompensa: '$383,000,000',
                estado: 'Vivo',
                altura: "277cm",
                epiteto: "Brook el Tarareador",
                nacimiento: "3 de abril",
                origen: "West Blue",
                aparicion: "Capitulo 442; Episodio 337",
                tipoFruta: "Paramecia",
                descripcion: 'Brook (ブルック Burukku), conocido como Soul King (ソウルキング Souru Kingu), es el músico de los Piratas de Sombrero de Paja, uno de sus dos espadachines y uno de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el noveno miembro de la tripulación y el octavo en unirse, haciéndolo al final del arco de Thriller Bark.',
                descripcion2: 'Brook consumió la fruta Yomi Yomi, que le permitió volver a la vida después de la muerte una vez. Brook aprendió con el tiempo a aprovechar más profundamente los poderes de su fruta del Diablo, dándole un control significativo sobre su propia alma y las almas de los demás.Originario del West Blue, Brook ejerció de guardia real de un reino, y posteriormente se haría miembro de los Piratas Rumbar. Murió y resucitó gracias al poder de su fruta. Sin embargo, debido al tiempo que tardó su alma en encontrar su cuerpo, quedó reducido a un esqueleto, conservando intacto únicamente su afro. Brook vagó solo por el Florian Triangle durante cincuenta años, conociendo finalmente a Luffy y sirviendo como aliado de los Sombrero de Paja durante el arco de Thriller Bark antes de unirse oficialmente a la tripulación. Su sueño es reunirse con su viejo amigo Laboon en la Reverse Mountain, donde vive con Crocus.'
            },
            {
                imagen: "./assets/personajes/jinbei.webp",
                nombre: 'Jinbe',
                fruta: 'Sin fruta',
                rol: 'Timonel',
                edad: 46,
                recompensa: '$1,100,000,000',
                estado: 'Vivo',
                altura: "301cm",
                epiteto: "El Caballero del Mar",
                nacimiento: "2 de abril",
                origen: "Reino de Ryugu",
                aparicion: "Capitulo 69; Episodio 31",
                tipoFruta: "Sin Fruta",
                descripcion: 'Jinbe el Caballero del Mar (海侠のジンベエ Kaikyō no Jinbē) es el timonel de los Piratas de Sombrero de Paja y uno de los oficiales principales de la Gran Flota de Sombrero de Paja, siendo el décimo miembro de la banda y el noveno en unirse.[3] Es un gyojin tiburón ballena, que sirvió como antiguo capitán de los Piratas del Sol[11] y como miembro de los Siete Señores de la Guerra del Mar.',
                descripcion2: 'Su nombre fue mencionado por primera vez por Yosaku cuando explicó el sistema de los Siete Señores de la Guerra del Mar. Sin embargo, fue introducido mucho más tarde en el arco de Impel Down. Renunció a su título como uno de los Siete Señores de la Guerra del Mar en la Batalla de Marineford, aliándose a los Piratas de Barbablanca. Durante la guerra formó una amistad con Monkey D. Luffy, y más tarde se alió con él para evitar el golpe de estado de los Nuevos Piratas Gyojin a la familia Neptune y al Reino de Ryugu. Incluso fue invitado a unirse a los Piratas de Sombrero de Paja, pero declinó debido a que aún estaba afiliado a Big Mom; sin embargo, afirmó que una vez termine sus asuntos pendientes él aceptaría y se uniría a la tripulación.Tras los hechos ocurridos en Whole Cake Island y finalizar sus cabos sueltos, Jinbe se rebeló contra la tripulación de Linlin y decidió ayudar a los de Sombrero de Paja a escapar de sus garras. Formó parte de una alianza con el equipo de recuperación de Sanji y los Piratas Fire Tank con el objetivo de asesinar a Big Mom, abandonando oficialmente su tripulación.'
            }
        ],

        otros: [
            {
                imagen: "./assets/personajes/ace.webp",
                nombre: "Portgas D. Ace",
                fruta: 'Mera Mera no mi',
                rol: "Comandante de la 2º división de los Piratas de Barbablanca",
                edad: 20,
                recompensa: "$550,000,000",
                estado: "Fallecido",
                altuta: "185cm",
                epiteto: "Ace puño de fuego",
                nacimiento: "1 de enero",
                origen: "South Blue",
                aparicion: "capitulo 154; episodio 91",
                tipoFruta: "Logia",
                descripcion: "Portgas D. Ace (ポートガス・D・エース Pōtogasu Dī Ēsu?), nacido como Gol D. Ace (ゴール・D・エース Gōru D. Ēsu?), y apodado Ace «Puño de Fuego» (火拳のエース Hiken no Ēsu?), fue el hermano mayor jurado de Luffy y Sabo y el hijo biológico del difunto Rey de los Piratas, Gol D. Roger, y Portgas D. Rouge. Ace fue adoptado por Monkey D. Garp, como había pedido el mismo Roger antes de su ejecución. También fue el comandante de la 2º división de los Piratas de Barbablanca y antiguo capitán de los Piratas Spade.",
                descripcion2: 'Los eventos que acontecieron durante el arco de Impel Down y de Marineford giran en torno al rescate organizado por su hermano Luffy y su capitán Barbablanca (quien para Ace, era más bien un verdadero padre) para salvarlo de ser ejecutado por el Gobierno Mundial. Esto desencadenó en una encarnizada guerra en la que Barbablanca y sus aliados se enfrentaron a la Marina y los Siete Señores de la Guerra del Mar, que cambió el curso de la historia. Ace fue liberado en el tramo final de la guerra, pero sacrificó su vida para proteger a Luffy del almirante de la Marina Akainu. La muerte de Ace finalmente resultó ser el catalizador que llevó a Luffy a entrenar durante dos años para volverse lo suficientemente fuerte como para proteger a sus amigos, siendo uno de los grandes puntos de inflexión de la primera mitad de la obra.'
            },
            {
                imagen: "./assets/personajes/sabo.webp",
                nombre: "Sabo",
                fruta: "Mera Mera no mi",
                rol: "Jefe de personal del Ejército Revolucionario",
                edad: 22,
                recompensa: "Desconocida",
                estado: "Vivo",
                altura: "187cm",
                epiteto: "El Emperador de las Llamas",
                nacimiento: "20 de marzo",
                origen: "East Blue",
                aparicion: "Capitulo 583; Episodio 494",
                tipoFruta: "Logia",
                descripcion: 'Sabo (サボ Sabo), también conocido como el Emperador de las Llamas (炎帝 Entei), es el jefe de personal del Ejército Revolucionario y, como tal, nº 2 de la organización. Es hermano por juramento de Monkey D. Luffy y del fallecido Portgas D. Ace, y un anterior noble del Reino de Goa.[3] En su niñez, Sabo fue dado por muerto luego de que un Noble Mundial le disparase a su balsa y ésta fuese destruida, pero fue salvado antes de ahogarse por Monkey D. Dragon, sin embargo, quedó amnésico perdiendo todos sus recuerdos. Tras la Batalla de Marineford, Sabo recuperó la memoria y posteriormente se reencontró con Luffy durante el arco de Dressrosa, siendo un aliado de éste allí y en las películas One Piece Film: Gold y One Piece: Stampede.',
                descripcion2: 'Durante el Arco del País de Wano, Sabo fue testigo de la existencia de Imu y del asesinato de Nefertari Cobra por éste y los cinco ancianos, y posteriormente incriminado por dicho asesinato. Su nueva reputación inspiró una nueva ola de revueltas contra el Gobierno Mundial en todo el mundo.'
            },
            {
                imagen: "./assets/personajes/goldroger.webp",
                nombre: "Gol D. Roger",
                fruta: "Sin Fruta",
                rol: "Capitan de los Piratas de Roger",
                edad: 53,
                recompensa: "$5,564,800,000",
                estado: "Fallecido",
                altura: "274cm",
                epiteto: "EL Rey de los Piratas",
                nacimiento: "31 de diciembre",
                origen: "East Blue",
                aparicion: "Capitulo 1; Episodio 1",
                tipoFruta: "Sin Fruta",
                descripcion: 'Gol D. Roger (ゴール・D・ロジャー Gōru dī Rojā) mejor conocido como Gold Roger (ゴールド・ロジャー Gōrudo Rojā), fue el capitán de los Piratas de Roger, siendo a su vez conocido como el Rey de los Piratas (海賊王 Kaizoku-Ō), título que le fue concedido tras conquistar todo el Grand Line, y al ser el dueño del legendario tesoro conocido como «One Piece» tras ser el primero junto a su tripulación en llegar a Laugh Tale en los últimos ochocientos años.',
                descripcion2: 'También fue el amante de Portgas D. Rouge y el padre biológico de Portgas D. Ace.'
            },
            {
                imagen: "./assets/personajes/shirohige.webp",
                nombre: "Edward Negwate",
                fruta: "Gura Gura no mi",
                rol: "Capitan de los Piratas de Shirohige",
                edad: 72,
                recompensa: "$5,046,000,000",
                estado: "Fallecido",
                altura: "666cm",
                epiteto: "Barbablanca",
                nacimiento: "6 de abril",
                origen: "Grand Line",
                aparicion: "Capitulo 234; Episodio 151",
                tipoFruta: "Paramecia",
                descripcion: 'Edward Newgate (エドワード・二ューゲート Edowādo Nyūgēto?), más conocido como Barbablanca (白ひげ Shirohige?), fue el capitán de los Piratas de Barbablanca y el histórico rival de Gol D. Roger. Tras la muerte de este, fue conocido como el Hombre más cercano al One Piece (ワンピースに最も近い男 Wan Pīsu ni mottomo chikai otoko), además de ser reconocido como el Hombre más fuerte del Mundo (世界最強の男 Sekai saikyō no otoko?.',
                descripcion2: 'En el pasado, antes de formar su propia tripulación, fue miembro de los legendarios Piratas de Rocks y más tarde en la vida se convirtió en uno de los Cuatro Emperadores que gobiernan el Nuevo Mundo, hasta su muerte en la Batalla de Marineford hace dos años.'
            },
            {
                imagen: "./assets/personajes/garp.webp",
                nombre: "Monkey D. Garp",
                fruta: "Sin Fruta",
                rol: "Vicealmirante de la Marina",
                edad: 78,
                recompensa: "$3,000,000,000",
                estado: "Vivo",
                altura: "287cm",
                epiteto: "El Heroe de la Marina",
                nacimiento: "2 de mayo",
                origen: "East Blue",
                aparicion: "Capitulo 92; Episodio 68",
                tipoFruta: "Sin Fruta",
                descripcion: 'Monkey D. Garp (モンキー・D・ガープ Monki Dī Gāpu?), más conocido por sus epítetos Garp el Puño (ゲンコツのガープ Genkotsu no Gāpu) o el Héroe de la Marina (海軍の英雄 Kaigun no Eiyū), es un vicealmirante del cuartel general de la Marina en calidad de instructor de nuevos reclutas extremadamente famoso y poderoso. Es el padre de Monkey D. Dragon,  el abuelo paterno de Monkey D. Luffy y el abuelo adoptivo de Portgas D. Ace. Fue responsable de supervisar el nacimiento de Ace y criar a un joven Luffy, antes de confiarlos a ambos a la Familia Dadan.',
                descripcion2: 'Garp es una figura importante, junto con Kong, Sengoku, Shiki , Silvers Rayleigh , Tsuru y Barbablanca, de los tiempos en el que Gol D. Roger , el "Rey Pirata", estaba vivo. Sus hazañas como soldado de la Marina le valieron una inmensa notoriedad y prestigio, y sus acciones durante el Incidente de God Valley en particular le otorgaron el título de "Héroe de la Marina". Cabe destacar que a Garp se le ofreció el rango de Almirante varias veces a lo largo de su carrera, pero rechazó la oferta de ascenso cada vez debido a su profundo odio y desprecio por los Nobles Mundiales . También es el ex mentor de Kuzan.Garp fue presentado por primera vez durante el Diario de Kobymeppo, donde se hizo cargo del entrenamiento de Koby y Helmeppo. Después de la guerra y la muerte de Ace, se convirtió en Instructor de la Marina para entrenar a nuevos reclutas, aunque aún conserva el rango de Vicealmirante,  no es conocido por el público y parece que se ha retirado.  Durante su misión para rescatar a Koby de los Piratas de Barbanegra, Garp resultó gravemente herido y se vio obligado a quedarse atrás, y como resultado, ha sido declarado "desaparecido en acción".'
            },
            {
                imagen: "./assets/personajes/dragon.webp",
                nombre: "Monkey D. Dragon",
                fruta: "Desconocido",
                rol: "Comandante Supremo del Ejercito Revolucionario",
                edad: 55,
                recompensa: "Desconocida",
                estado: "Vivo",
                altura: "256cm",
                epiteto: "Dragon el Revolucionario",
                nacimiento: "5 de octubre",
                origen: "East Blue",
                aparicion: "Capitulo 100; Episodio 52",
                tipoFruta: "Desconocido",
                descripcion: 'Monkey D. Dragon (モンキー・D・ドラゴン Monkī Dī Doragon?),[4] conocido como el Peor Criminal del Mundo (世界最悪の犯罪者 Sekai Saiaku no Hanzaisha), es el comandante supremo del Ejército Revolucionario y el criminal más buscado y peligroso del mundo. Es el padre de Monkey D. Luffy, hijo de Monkey D. Garp y la mayor amenaza del Gobierno Mundial.',
                descripcion2: ''
            },
            {
                imagen: "./assets/personajes/kurohige.webp",
                nombre: "Marshall D. Teach",
                fruta: "Yami Yami no mi, Gura Gura No mi",
                rol: "Capitan de los Piratas de Kurohige",
                edad: 40,
                recompensa: "$3,996,000,000",
                estado: "Vivo",
                altura: "344cm",
                epiteto: "Barbanegra",
                nacimiento: "3 de agostp",
                origen: "Grand Line",
                aparicion: "Capitulo 223; Episodio 146",
                tipoFruta: "Logia, Paramecia",
                descripcion: 'Marshall D. Teach (マーシャル・D・ティーチ Māsharu Dī Tīchi), más conocido como Barbanegra (黒ひげ Kurohige) es el almirante de los Piratas de Barbanegra y uno de los Cuatro Emperadores que gobiernan los mares del Nuevo Mundo, estatus que consolidó tras su victoria en la Batalla de la Venganza frente a los Piratas de Barbablanca. Actualmente él y su banda se encuentran ocupando Hachinosu.',
                descripcion2: 'Inicialmente un aprendiz pirata, Teach formó parte de la segunda división de los Piratas de Barbablanca bajo mando directo de Portgas D. Ace, a quien entregó a la Marina tras el Duelo en la Isla Banaro para posicionarse como uno de los Siete Guerreros del Mar. Fue también el artífice de la masiva liberación de presos en el último nivel de Impel Down. Sus acciones le llevaron a ser visto como uno de los piratas conocidos como "La Peor Generación".Actuó como antagonista menor en el arco de Jaya, en el de Impel Down, y como uno de los antagonistas principales en el arco de Marineford al ser él su principal desencadenante. Los distintos sucesos acaecidos le sitúan como uno de los antagonistas principales de la serie.'
            },
            {
                imagen: "./assets/personajes/shanks.webp",
                nombre: "Shanks",
                fruta: "Sin Fruta",
                rol: "Capitan de los piratas del Pelirojo",
                edad: 39,
                recompensa: "$4,048,900,000",
                estado: "Vivo",
                altura: "199cm",
                epiteto: "Shanks el pelirojo",
                nacimiento: "9 de marzo",
                origen: "West Blue",
                aparicion: "Capitulo 1; Episodio 4",
                tipoFruta: "Sin Fruta",
                descripcion: 'Shanks el Pelirrojo (赤髪あかがみのシャンクス Akagami no Shankusu), es el capitán de los Piratas del Pelirrojo y uno de los Cuatro Emperadores que gobiernan el Nuevo Mundo. Fue, además, un miembro de la legendaria tripulación de Gol D. Roger, siendo la única banda que logró conquistar con éxito todo Grand Line.',
                descripcion2: 'Es el hombre que inspiró a Luffy a seguir su sueño de ser el Rey de los Piratas, y el que encontró la fruta Gomu Gomu que Luffy comió accidentalmente. Es también el padre adoptivo de Uta.'
            },
            {
                imagen: "./assets/personajes/kaido.webp",
                nombre: "Kaido",
                fruta: "Uo Uo no Mi, Moderu: Seiryū",
                rol: "Capitan de los Piratas Bestias",
                edad: 59,
                recompensa: "$4,611,100,000",
                estado: "Desconocido",
                altura: "710",
                epiteto: "Kaido de las Bestias",
                nacimiento: "1 de mayo",
                origen: "Deconocido",
                aparicion: "Capitulo 795; Episodio 739",
                tipoFruta: "Zoan Mitica",
                descripcion: 'Kaidou de las Bestias (百獣のカイドウ Hyakujū no Kaidō, España: «Kaido el Cien Bestias») conocido también como la Criatura más Poderosa (最強の生物 Saikyō no Seibutsu), es el gobernador general de los Piratas de las Bestias y ejerció como uno de los Cuatro Emperadores hasta que perdió dicho título cuando fue derrotado durante el asalto a Onigashima. Fue además un aprendiz de los legendarios Piratas de Rocks durante su juventud. Fue el tercer emperador en ser mencionado y el último en hacer aparición.',
                descripcion2: 'La primera referencia que se tiene de él vino de Monkey D. Garp en Water 7 y fue directamente mencionado por Gecko Moria poco después de tener en su poder la sombra de Monkey D. Luffy. Su posición como uno de los Cuatro Emperadores fue revelada después de que los Piratas de Sombrero de Paja derrotasen a Moria. Debido a su papel y acciones es el antagonista principal del arco del País de Wano así como de la saga del País de Wano y junto a Charlotte Linlin el antagonista más notable y destacado de la segunda mitad de la historia.'
            },
            {
                imagen: "./assets/personajes/bigmom.webp",
                nombre: "Charlotte Linlin",
                fruta: "Soru Soru no mi",
                rol: "Capitana; Reina de Totto Land",
                edad: 68,
                recompensa: "$4,388,000,000",
                estado: "Desconocido",
                altura: "880cm",
                epiteto: "Big Mom",
                nacimiento: "15 de febrero",
                origen: "Grand Line",
                aparicion: "Capitulo 651; Episodio 571",
                tipoFruta: "Paramecia",
                descripcion: 'Charlotte Linlin (シャー ロット リンリン Shārotto Rinrin), más conocida como Big Mom (マム ビッグ Biggu Mamu, lit. «Gran Mamá»), es la capitana de los Piratas de Big Mom, matriarca de la familia Charlotte, reina de Totto Land y fue uno de los Cuatro Emperadores que gobiernan los mares del Nuevo Mundo, hasta que perdió dicha posición tras su derrota a manos de Trafalgar D. Water Law y Eustass Kid. Al igual que varios piratas del pasado de renombre, fue miembro de los Piratas de Rocks.',
                descripcion2: 'Actúa como antagonista principal en el arco de Whole Cake Island, así como antagonista secundaria del arco del País de Wano y junto a Kaidou es una de las antagonistas más notables y destacadas de la segunda mitad de la historia. Big Mom es una enorme y obesa mujer rolliza con el rostro grotesco y arrugado. Debido a su gordura, su mandíbula y su barbilla apenas sobresalen, concentrándose en una notable papada. Generalmente suele sonreír, mostrando su amplia boca, de labios gruesos pintados de rojo, dientes grandes y redondos y una larga lengua que a menudo saca. Su pelo le llega hasta la mitad de la espalda, es de color rosa claro y especialmente rizado. Sus ojos son de color naranja y están maquillados con sombra de ojos lila y raya rosa. Su nariz tiene forma de pico y sus mejillas son redondas y salientes. En su brazo izquierdo porta un tatuaje en forma de corazón rojo rodeado por finas líneas negras que enmarcan sus extremos.'
            }

        ]
    }
}