export const data = {
    personajes : {
        mugiwaras: [
            {
                imagen: "./assets/luffy.webp",
                nombre: 'Monkey D. Luffy',
                fruta: 'Gomu-Gomu no mi',
                rol: 'Capitan',
                edad: 19,
                recompensa: '$3,000,000,000',
                estado: 'Vivo',
                altura: "172cm",
                epiteto: "Sombrero de paja Luffy",
                nacimiento: "5 de mayo",
                origen: "East Blue",
                aparicion: "Capitulo 1; Episodio 1",
                tipoFruta: "Zoan Mitica",
                descripcion: 'Monkey D. Luffy (モンキー・Ｄ・ルフィ Monkī Dī Rufi?), más conocido como Luffy «Sombrero de Paja» (麦わらのルフィ Mugiwara no Rufi), es el protagonista principal de la serie de manga y anime One Piece. Es el capitán y fundador de los Piratas de Sombrero de Paja así como un de los Cuatro Emperadores que gobiernan los mares del Nuevo Mundo. Comió una fruta del diablo llamada fruta Gomu Gomu, que le convirtió en un hombre de goma. Además de esto, posee varias habilidades que le hacen ser un pirata más que especial; un gran ejemplo de ello es la capacidad de usar el haoshoku haki ―que sólo lo posee una persona dentro de un millón― y poseer también los otros dos tipos de haki.',
                descripcion2: 'Luffy pertenece a una familia plagada de personajes conocidos mundialmente: es hijo del líder del Ejército Revolucionario y criminal más buscado del mundo, Monkey D. Dragon; nieto del héroe de la Marina y anterior vicealmirante Monkey D. Garp, hermano adoptivo del conocido pirata Ace "Puño de Fuego" ―antiguo comandante de la segunda división de los Piratas de Barbablanca―, así como del oficial general del Ejército Revolucionario, Sabo. Su objetivo en la vida es convertirse en el próximo Rey de los Piratas, encontrar el legendario tesoro conocido como el "One Piece", que perteneció al anterior Rey de los Piratas Gol D. Roger, y conquistar el Nuevo Mundo liderando una tripulación formada por grandes piratas.'
            },
            {
                imagen: "./assets/zoro.webp",
                nombre: 'Roronoa Zoro',
                fruta: 'Sin fruta',
                rol: 'Espadachin',
                edad: 21,
                recompensa: '$1,111,000,000',
                estado: 'Vivo',
                altura: "181cm",
                epiteto: "El Cazador de Piratas",
                nacimiento: "11 de noviembre",
                origen: "East Blue",
                aparicion: "Capitulo 2; Episodio 1",
                tipoFruta: "Sin Fruta",
                descripcion: 'Roronoa Zoro (ロロノア・ ゾロ Roronoa Zoro?), conocido como El Cazador de Piratas (海賊狩り Kaizoku Gari?),[16] es el primer pirata que se unió a Monkey D. Luffy, y el principal combatiente de los Piratas de Sombrero de Paja, uno de sus dos espadachines y uno de los oficiales principales de la Gran Flota de Sombrero de Paja, así como un antiguo cazarrecompensas.',
                descripcion2: 'Nacido en el East Blue, Zoro es hijo de Tera y Roronoa Arashi, nieto de Shimotsuki Furiko y Roronoa Pinzoro, y sobrino nieto de Shimotsuki Ushimaru, lo que le convierte en descendiente matrilineal tanto de la familia Shimotsuki del País de Wano como del legendario samurái Shimotsuki Ryuma. Fue el primer miembro en unirse a la tripulación, y es considerado parte del Trío Monstruoso (怪物三人組 Kaibutsu San-ningumi) junto a Luffy y Sanji. Su sueño es convertirse en el mejor espadachín del mundo. Zoro junto a su capitán, también es considerado uno de los Once Supernovas que forman parte de «la peor generación».Obtuvo su primera recompensa de $60.000.000 tras el arco de Arabasta. Más tarde aumentó a Belly120.000.000 tras el incidente de Enies Lobby, y de nuevo a Belly320.000.000 tras el arco de Dressrosa. Tras el asalto a Onigashima, su recompensa aumentó a $1.111.000.000, siendo la segunda más alta de la tripulación solo superada por la de Luffy.'
            },
            {
                imagen: "./assets/nami.webp",
                nombre: 'Nami',
                fruta: 'Sin fruta',
                rol: 'Navegante',
                edad: 20,
                recompensa: '$366,000,000',
                estado: 'Viva',
                altura: "170cm",
                epiteto: "La Gata Ladrona",
                nacimiento: "3 de julio",
                origen: "East Blue",
                aparicion: "Capitulo 8; Episodio 1",
                tipoFruta: "Sin Fruta",
                descripcion: 'Nami (ナミ Nami), apodada Gata Ladrona (泥棒猫 Dorobō Neko), es una pirata y la navegante de los Piratas del Sombrero de Paja , así como una de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el tercer miembro de la tripulación y la segunda en unirse, haciéndolo oficialmente durante el arco de Arlong Park. Ella era anteriormente un miembro de los Piratas de Arlong e inicialmente se unió a los de Sombrero de Paja con el fin de robarles, pero se unió oficialmente tras rebelarse contra Arlong y su posterior derrota a manos de Luffy. Actualmente posee una recompensa de $366.000.000.',
                descripcion2: 'Nami es una chica joven, de tamaño normal con una constitución delgada, y que originalmente tenía el pelo corto de color naranja. En el anime ella fue el primer personaje principal en aparecer en el episodio 1 antes que Luffy (aunque en el manga apareció al principio del arco de la ciudad Orange). Muchas personas la consideran muy atractiva y hermosa, comparándola en una ocasión con una diosa. Ella tiene un tatuaje azul (negro en el manga) en su hombro izquierdo que representa una mandarina y un molinillo (un homenaje a Bell-mère y Genzo, respectivamente), en donde ella antes tenía un tatuaje que indicaba que ella era miembro de la banda de Arlong.'
            },
            {
                imagen: "./assets/usopp.webp",
                nombre: 'Usopp',
                fruta: 'Sin fruta',
                rol: 'Francotirador',
                edad: 19,
                recompensa: '$500,000,000',
                estado: 'Vivo',
                altura: "176cm",
                epiteto: "Rey de los Tiradores",
                nacimiento: "1 de abril",
                origen: "East Blue",
                aparicion: "Capitulo 23; Episodio 8",
                tipoFruta: "Sin Fruta",
                descripcion: 'Usopp (ウソップ Usoppu) es el francotirador de los Piratas de Sombrero de Paja y uno de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el cuarto miembro de la tripulación y el tercero en unirse oficialmente. A pesar de abandonar la banda en el arco de Water 7, se volvió a unir en el arco del regreso a Water 7.Es proveniente de la villa Syrup en el East Blue. Ahí ejerció como capitán de los Piratas de Usopp, pero tras los eventos del arco de Villa Syrup, se unió a los Sombrero de Paja. Su sueño es convertirse en un valiente guerrero de los mares como su padre. Su recompensa actual es de $500.000.000.',
                descripcion2: 'Durante la mayor parte de la historia, Usopp es un joven de piel blanca pero bronceada y constitución delgada, ojos grandes y redondos, labios gruesos y pelo negro muy rizado de longitud media; aunque el rasgo más llamativo de su apariencia es, sin duda, su larga nariz (que aparentemente es una alusión al personaje de Pinocho, el protagonista de un cuento del mismo nombre). Este llamativo rasgo fue aparentemente heredado de su madre, mientras que en todos los demás rasgos de su rostro es prácticamente idéntico a su padre (esto es notable incluso teniendo en cuenta que el aspecto de su padre ha sufrido muchos cambios con el paso del tiempo; sobre todo en lo referente al cabello, que pasa de ser igual de negro y rizado que el de su hijo a ser rubio y llevar rastas). En lo que se refiere a su cuerpo, Usopp es algo más alto que Luffy y su constitución es, si hacemos comparación, más semejante a la de Sanji y del capitán, que a la de Zoro o mucho menos Franky.'
            },
            {
                imagen: "./assets/sanji.webp",
                nombre: 'Vismoke Sanji',
                fruta: 'Sin fruta',
                rol: 'Cocinero',
                edad: 21,
                recompensa: '$1,032,000,000',
                estado: 'Vivo',
                altura: "180cm",
                epiteto: "Piernas Negras",
                nacimiento: "2 de marzo",
                origen: "North Blue",
                aparicion: "Capitulo 43; Episodio 20",
                tipoFruta: "Sin Fruta",
                descripcion: 'Sanji (サンジ Sanji?), conocido como Pierna Negra (黒脚 Kuro Ashi) y nacido como Vinsmoke Sanji (ヴィンスモーク・サンジ Vinsumōku Sanji), es el cocinero de los Piratas de Sombrero de Paja, así como uno de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el quinto miembro de la tripulación, y el cuarto en unirse. Él nació en el North Blue, siendo el primer tripulante en no ser originario del East Blue.',
                descripcion2: 'Nacido como el cuarto hijo de la familia Vinsmoke, y por ende como uno de los príncipes del Reino de Germa, Sanji se exilió de su país y renegó de su familia, yéndose al East Blue y pasando a trabajar como cocinero en el Baratie, hasta que decidió unirse a la banda. Es considerado parte del Trío Monstruoso (怪物三人組 Kaibutsu San-ningumi) junto a Luffy y Zoro; y, como tal, es uno de los combatientes más fuertes de la tripulación. Su sueño es encontrar el mar legendario conocido como All Blue.Actualmente posee una recompensa de $1.032.000.000 que obtuvo después de los acontecimientos del arco del País de Wano, siendo la cuarta recompensa más alta de la tripulación superada por la de Luffy, Zoro y Jinbe'

            },
            {
                imagen: "./assets/chopper.webp",
                nombre: 'Tony Tony Chopper',
                fruta: 'Hito-Hito no mi',
                rol: 'Medico',
                edad: 17,
                recompensa: '$1000',
                estado: 'Vivo',
                altura: "90cm",
                epiteto: "El Amante del Algodón de Azúcar",
                nacimiento: "24 de diciembre",
                origen: "Paradise",
                aparicion: "Capitulo 134; Episodio: 81",
                tipoFruta: "Zoan",
                descripcion: 'Tony Tony Chopper (トニートニー・チョッパー Tonī Tonī Chopā?) es el médico de los Piratas de Sombrero de Paja, así como uno de los oficiales principales de la Gran Flota de Sombrero de Paja. Es un reno que comió la fruta Hito Hito de la isla de Drum. Él es el sexto miembro de la tripulación y el quinto en unirse a ella.',
                descripcion2: 'Es un Reno de nariz azul que comió la fruta Hito Hito, adquiriendo forma e inteligencia humana. La mayor parte del tiempo, Chopper mantiene un tamaño pequeño, con forma de reno-humanoide (brain point); las habilidades de su fruta del diablo le permiten cambiar de apariencia dependiendo de la situación. El cuerno izquierdo de Chopper tiene una placa metálica alrededor porque se lo rompió en una pelea cuando era más joven, y Hiriluk se lo trató. Chopper tiene un rasgo destacable que ningún otro reno tiene: su nariz azul.Varios personajes en One Piece han pensado al principio que Chopper es un mapache (del japonés "tanuki"), debido al aspecto que tiene cuando se halla en su forma "Brain Point". En realidad se trata de un juego de palabras: el término japonés "tonakai", que significa reno, es de donde viene el "Tony" del nombre completo de Chopper. A diferencia de su "Brain Point", cuando Chopper está en su "Heavy Point", es confundido con un gorila o un yeti.'
            },
            {
                imagen: "./assets/robin.webp",
                nombre: 'Nico Robin',
                fruta: 'Hana-Hana no mi',
                rol: 'Arqueologa',
                edad: 30,
                recompensa: '$930,000,000',
                estado: 'Viva',
                altura: "188cm",
                epiteto: "La Niña Demonio",
                nacimiento: "6 de febrero",
                origen: "West Blue",
                aparicion:"Cpitulo 114; Episodio 67",
                descripcion: 'Nico Robin (ニコ・ロビン Niko Robin), también conocida por sus epítetos: Niña Demonio (悪魔の子 Akuma no Ko) y La Luz de la Revolución (革命の灯 Kakumei no Tomoshibi) es la arqueóloga de los Piratas de Sombrero de Paja, así como una de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el séptimo miembro de la tripulación y el sexto en unirse, haciéndolo al final del arco de Arabasta.',
                descripcion2: 'Es introducida como una de los antagonistas secundarios más destacados de la saga de Arabasta siendo la vicepresidenta de Baroque Works y la mano derecha de Crocodile. Sin embargo, luego de ser salvada por Monkey D. Luffy de morir a manos de Crocodile y la posterior derrota del ex Señor de la Guerra del Mar se une a la tripulación. Dejó temporalmente a la banda durante el arco de Water 7, pero se reincorporó al final del arco de Enies Lobby tras la derrota del CP9 a manos de los Piratas de Sombrero de Paja.Su sueño es conocer la verdadera historia investigando en los poneglyphs. Actualmente ofrecen una recompensa de $930.000.000 por su cabeza, siendo la quinta más alta de toda su tripulación.'
            },
            {
                imagen: "./assets/franky.webp",
                nombre: 'Franky',
                fruta: 'Sin fruta',
                rol: 'Carpintero',
                edad: 36,
                recompensa: '$394,000,000',
                estado: 'Vivo',
                altura: "240cm",
                epiteto: "El Hombre de Hierro",
                nacimiento: "9 de marzo",
                origen: "South Blue",
                aparicion: "Capitulo 329; Episodio 233",
                tipoFruta: "Sin Fruta",
                descripcion: 'Franky (フランキー Furankī), apodado el Hombre de Hierro (鉄人 tetsujin), es el carpintero naval de los Piratas de Sombrero de Paja y uno de los oficiales principales de la Gran Flota de Sombrero de Paja. Es el octavo miembro de la tripulación y el séptimo en unirse, haciéndolo al final del arco del regreso a Water 7.',
                descripcion2: "Nacido como Cutty Flam (カティ・フラム Kati Furamu) y originario del South Blue, Franky fue un miembro de los Tom's Workers, hasta que un incidente que dañó su cuerpo le requirió convertirse en un cyborg para curarse. Posteriormente se convertiría en el líder de la familia Franky, un grupo de cazarrecompensas y desmanteladores de barcos, adoptando su nombre actual para ocultar su identida.Franky y sus seguidores eran originalmente enemigos de los Sombrero de Paja al principio del arco de Water 7, hasta que las circunstancias les obligaron a convertirse en aliados al final del mismo arco y del arco de Enies Lobby. El sueño de Franky es crear un barco y circunnavegar el mundo con él, y construyó el Thousand Sunny y se unió a los Piratas de Sombrero de Paja para cumplir su sueño."
            },
            {
                imagen: "./assets/brook.webp",
                nombre: 'Brook',
                fruta: 'Yomi-Yomi no mi',
                rol: 'Musico',
                edad: 90,
                recompensa: '$383,000,000',
                estado: 'Vivo'
            },
            {
                imagen: "./assets/jinbei.webp",
                nombre: 'Jinbe',
                fruta: 'Sin fruta',
                rol: 'Timonel',
                edad: 46,
                recompensa: '$1,100,000,000',
                estado: 'Vivo'
            }
        ],

        otros: [
            {
                imagen: "./assets/ace.webp",
                nombre: "Portgas D. Ace",
                fruta: 'Mera Mera no mi',
                rol: "Comandante de la 2º división de los Piratas de Barbablanca",
                edad: 20,
                recompensa: "$550,000,000",
                estado: "Fallecido",
                altuta: "185cm",
                epiteto: "Ace puño de fuego",
                nacimiento: "1 de enero",
                origen: "South Blue",
                aparicion: "capitulo 154; episodio 91",
                tipoFruta: "Logia",
                descripcion: "Portgas D. Ace (ポートガス・D・エース Pōtogasu Dī Ēsu?), nacido como Gol D. Ace (ゴール・D・エース Gōru D. Ēsu?), y apodado Ace «Puño de Fuego» (火拳のエース Hiken no Ēsu?), fue el hermano mayor jurado de Luffy y Sabo y el hijo biológico del difunto Rey de los Piratas, Gol D. Roger, y Portgas D. Rouge. Ace fue adoptado por Monkey D. Garp, como había pedido el mismo Roger antes de su ejecución. También fue el comandante de la 2º división de los Piratas de Barbablanca y antiguo capitán de los Piratas Spade."
            }
        ]
    }
}